### ISSUE TITLE
上传文件会遇到panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kangear** [aliyun/ossutil#108]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6feeec]

goroutine 43 [running]:
github.com/aliyun/ossutil/lib.(*CopyCommand).uploadFileWithReport(0xb41c00, 0xc0001ba870, 0x7ffc16ca61c6, 0x12, 0x7ffc16ca61cc, 0x6, 0x7ffc16ca61d3, 0x5, 0x7ffc16ca61af, 0x16, ...)
	/root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:1922 +0x31c
github.com/aliyun/ossutil/lib.(*CopyCommand).uploadConsumer(0xb41c00, 0xc0001ba870, 0x7ffc16ca61c6, 0x12, 0x7ffc16ca61cc, 0x6, 0x7ffc16ca61d3, 0x5, 0xc0001d6780, 0xc0001d67e0)
	/root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:1871 +0x199
created by github.com/aliyun/ossutil/lib.(*CopyCommand).uploadFiles
	/root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:1557 +0x401
```
频繁遇到，重启后又正常。过一段时间又遇到。

**Comment by gahoo** [comment]
树莓派4上arm32架构1.6.10版本碰到类似问题。当分块上传大文件时出现错误：

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 `pc=0x11c08]`

goroutine 16 [running]:
runtime/internal/atomic.goLoad64(0x1a0e08c, 0x0, 0x383f00)
        /root/go_install/go/src/runtime/internal/atomic/atomic_arm.go:124 +0x1c
github.com/aliyun/ossutil/lib.(*OssResumeProgressListener).Retry(0x1a0e080)
        /root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:149 +0x28
github.com/aliyun/ossutil/lib.(*CopyCommand).ossResumeUploadRetry(0x650d68, 0x180f480, 0xbe98976e, 0x11, 0x18157a0, 0x1a, 0x2711f4, 0x0, 0x1a18000, 0x3, ...)
        /root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:2205 +0x70
github.com/aliyun/ossutil/lib.(*CopyCommand).uploadFile(0x650d68, 0x180f480, 0xbe989780, 0xd, 0xbe989786, 0x6, 0xbe989786, 0x0, 0xbe98976e, 0x11, ...)
        /root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:2034 +0x988
github.com/aliyun/ossutil/lib.(*CopyCommand).uploadFileWithReport(0x650d68, 0x180f480, 0xbe989780, 0xd, 0xbe989786, 0x6, 0xbe989786, 0x0, 0xbe98976e, 0x11, ...)
        /root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:1939 +0x64
github.com/aliyun/ossutil/lib.(*CopyCommand).uploadConsumer(0x650d68, 0x180f480, 0xbe989780, 0xd, 0xbe989786, 0x6, 0xbe989786, 0x0, 0x1858980, 0x18589c0)
        /root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:1906 +0xf8
created by github.com/aliyun/ossutil/lib.(*CopyCommand).uploadFiles
        /root/go_project/src/github.com/aliyun/ossutil/lib/cp.go:1578 +0x284
```

**Comment by gahoo** [comment]
du命令也会有类似的错误

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11c08]

goroutine 1 [running]:
runtime/internal/atomic.goLoad64(0x650174, 0x140f3e0, 0x0)
	/root/go_install/go/src/runtime/internal/atomic/atomic_arm.go:124 +0x1c
github.com/aliyun/ossutil/lib.(*DuCommand).RunCommand(0x6500b8, 0x360518, 0x6500b8)
	/root/go_project/src/github.com/aliyun/ossutil/lib/du.go:174 +0x260
github.com/aliyun/ossutil/lib.(*CommandManager).RunCommand(0x1433e9c, 0xbedb078c, 0x2, 0x140ee48, 0x1, 0x3, 0x140ee20, 0xbf8ee559, 0xab0b61, 0x39f14)
	/root/go_project/src/github.com/aliyun/ossutil/lib/command_manager.go:120 +0xec
github.com/aliyun/ossutil/lib.RunCommand(0x140ee40, 0x2, 0x4, 0x140ee20, 0xab0b61, 0x0, 0x653918)
	/root/go_project/src/github.com/aliyun/ossutil/lib/command_manager.go:94 +0xb0
github.com/aliyun/ossutil/lib.ParseAndRunCommand(0x0, 0x0)
	/root/go_project/src/github.com/aliyun/ossutil/lib/command_manager.go:57 +0x3b0
main.main()
	/root/go_project/src/github.com/aliyun/ossutil/ossutil.go:12 +0x14
```

**Comment by sweetOranges** [comment]
bucket object is not thread safe, maybe need lock
